### ISSUE TITLE
There was an unexpected error,Request Id: 80000006-0000-d400-b63f-84710c7967bb

### ISSUE THREAD

**Issue by tiandao-dongguan** [ranga543/IdentityServer3.Dapper#2]
this is  a great repository,thank you very much! 
i flow this :
1.create database Sample.IdSvr,run "all.sql".
2.create database Sample,run "
       CREATE TABLE [dbo].[Users](
	[Id] [varchar](50) NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL
) ON [PRIMARY]"
3.run  this project ,click “application permissions ” in Welcome page, show me that"There was an unexpected error,Request Id: 80000006-0000-d400-b63f-84710c7967bb".
4.run  \webapi\test ,is ok.
why ? Am I missing a database seed file?Did I miss something ?
need your help,thank you . i hope you  give everyone a introduction document 。

**Comment by ranga543** [comment]
May I know version of nuget package you installed ?

**Comment by tiandao-dongguan** [comment]
oh, of course,thank you .
 core.dapper:
 <package id="Dapper" version="1.50.2" targetFramework="net45" />
  <package id="IdentityServer3" version="2.5.4" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net45" />
  <package id="Owin" version="1.0" targetFramework="net45" />
IdentityServer3.Dapper.Sample.Auth:
<package id="Dapper" version="1.50.2" targetFramework="net45" />
  <package id="IdentityServer3" version="2.5.4" targetFramework="net45" />
  <package id="IdentityServer3.Dapper" version="1.0.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.0" targetFramework="net45" />
  <package id="Microsoft.Net.Compilers" version="1.0.0" targetFramework="net45" developmentDependency="true" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net45" />
  <package id="Owin" version="1.0" targetFramework="net45" />

**Comment by tiandao-dongguan** [comment]
@ranga543 
`<package id="Dapper" version="1.50.2" targetFramework="net45" />
  <package id="IdentityServer3" version="2.5.4" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net45" />
  <package id="Owin" version="1.0" targetFramework="net45" />`

`<package id="Dapper" version="1.50.2" targetFramework="net45" />
  <package id="IdentityServer3" version="2.5.4" targetFramework="net45" />
  <package id="IdentityServer3.Dapper" version="1.0.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.0" targetFramework="net45" />
  <package id="Microsoft.Net.Compilers" version="1.0.0" targetFramework="net45" developmentDependency="true" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net45" />
  <package id="Owin" version="1.0" targetFramework="net45" />`

**Comment by ranga543** [comment]
Are you directly click on the application permission after you run IdentityServer3.Dapper.Sample.Auth ?
If you do that it will not show login page (that page has to requested by the client) the request has to come from client then it will show up login page.
Please check IdentityServer3 client samples [here](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients)

**Comment by tiandao-dongguan** [comment]
just you write,OK,thank you very much,
