### ISSUE TITLE
Allow schema setup

### ISSUE THREAD

**Issue by newverdun** [ranga543/IdentityServer3.Dapper#4]
All tables are in the dbo schema, there should be a configuration to configure a custom schema, thinking about complex environments.

_Sorry for my bad spelling, this is not my native language :-)_

**Comment by clabnet** [comment]
Interesting, There are samples data ?

**Comment by ranga543** [comment]
You can always use [IdentityServer3.EntityFramework](https://github.com/IdentityServer/IdentityServer3.EntityFramework) as a reference. Your always welcome to create PR.
